{% set name = "nceplibs-g2c" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-g2c/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cf0ac8f75aed662ccc64f4c44fbe46a70307bc27cbe95417fdfb6caf75245457
  patches:
    - 0001-Trying-this-simple-change.patch

build:
  skip: true  # [win]
  number: 0

outputs:
  - name: {{ name }}
    script: build_linux.sh  # [not win]
    script: build_win.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}     # [not win]
        - cmake >=3.15
        - pkg-config >=0.21
        - make                  # [not win]
        - ninja                 # [win]
      host:
        - libpng
        - zlib
        # list libaec twice to conda-smithy doesn't get confused
        - libaec
        - libaec >=1.0.6
        - openjpeg              # [not win]
        - jasper                # [win]

    test:
      commands:
        - test -f ${PREFIX}/lib/libg2c${SHLIB_EXT}  # [not win]
        - test ! -f ${PREFIX}/lib/libg2c.a  # [not win]
        - if not exist %LIBRARY_BIN%\\g2c.dll exit 1  # [win]

  # old name for the package
  - name: g2clib
    requirements:
      run:
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libg2c${SHLIB_EXT}  # [not win]
        - test ! -f ${PREFIX}/lib/libg2c.a  # [not win]
        - if not exist %LIBRARY_BIN%\\g2c.dll exit 1  # [win]

  # old name for the package

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-g2c
  summary: This library contains C decoder/encoder routines for GRIB edition 2.
  license: LGPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
    - jhamman
    - xylar
    - TimothyCera-NOAA
    - EricEngle-NOAA
